# Automatically generated by configure - do not modify
SRC_PATH=/home/usr/workspace/vfresh/qemu/qemu-3.1.0/roms/seabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
